name: Terraform AWS Provisioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Environment Variables
        env:
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          echo "Valores"
          echo ${{ secrets.AWS_REGION }}
